circleci: Limit number of CPUs used in Linux cargo test (#93)
Summary:
The linux-build-and-test keeps failing (not always) with the following error:
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcBHQgh0/symbols.o" ... "/home/circleci/project/target/debug/deps/buck2-6f57e2aac7617637" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
          compilation terminated
```
See https://app.circleci.com/pipelines/github/facebookincubator/buck2/2762/workflows/7a3b999a-649a-41b5-9063-076331e1a0bd/jobs/7719

{F869547999}

Since this looks to be a resource problem, reduce the number of jobs used to build and test in cargo. A similar approach worked well for similar issues in macos.

Pull Request resolved: https://github.com/facebookincubator/buck2/pull/93

Reviewed By: stepancheg

Differential Revision: D43193936

Pulled By: themarwhal

fbshipit-source-id: 8607240e8459c23ac4f8c20e34b39481ed94e741