offline builds: Include directory entries in manifest output
Summary:
Turns out we actually need all the directory entries in the manifest, otherwise you get errors like:
```
[09:43:51 facebook@/// ~/fbsource]$ dotslash .buck2 build --no-remote-cache --local-only fbcode//mode/opt fbcode//scripts/skarlage/protobuf_parse:protobuf_parse
Soft Error: source_file_missing: Source file `fat.py` does not exist as a member of package `fbcode//buck2/platform/execution`.
Soft Error: source_file_missing: Source file `make_comp_db.py` does not exist as a member of package `prelude//cxx/tools`.
Soft Error: source_file_missing: Source file `dist_lto_planner.py` does not exist as a member of package `prelude//cxx/dist_lto/tools`.
Soft Error: source_file_missing: Source file `dist_lto_opt.py` does not exist as a member of package `prelude//cxx/dist_lto/tools`.
Soft Error: source_file_missing: Source file `dist_lto_prepare.py` does not exist as a member of package `prelude//cxx/dist_lto/tools`.
Soft Error: source_file_missing: Source file `dist_lto_copy.py` does not exist as a member of package `prelude//cxx/dist_lto/tools`.
Soft Error: source_file_missing: Source file `tests/test_dist_lto_opt.py` does not exist as a member of package `prelude//cxx/dist_lto/tools`.
Soft Error: source_file_missing: Source file `dist_lto_opt.py` does not exist as a member of package `prelude//cxx/dist_lto/tools`.
Soft Error: source_file_missing: Source file `find_and_replace.bat` does not exist as a member of package `prelude//tools`.
Soft Error: source_file_missing: Source file `include` does not exist as a member of package `fbcode//third-party-buck/platform010/build/llvm-fb/12`.
Error running analysis for `fbcode//scripts/skarlage/protobuf_parse:protobuf_parse (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#2e73eee9422a24d3)`

Caused by:
    0: Error looking up configured node fbcode//scripts/skarlage/protobuf_parse:protobuf_parse (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#2e73eee9422a24d3)
    1: Error checking compatibility of `fbcode//tools/build/buck/wrappers:cxx-platform010-clang-nosan-ar` with `fbcode//buck2/platform/execution:linux-x86_64#e7e3a16cfa456368`
    2: Error looking up configured node fbcode//tools/build/buck/wrappers:cxx-platform010-clang-nosan-ar (fbcode//buck2/platform/execution:linux-x86_64#e7e3a16cfa456368)
    3: Error looking up configured node fbcode//third-party-buck/platform010/build/llvm-fb/12:bin/llvm-ar (fbcode//buck2/platform/execution:linux-x86_64#e7e3a16cfa456368)
    4: looking up unconfigured target node `fbcode//third-party-buck/platform010/build/llvm-fb/12:bin/llvm-ar`
    5: Error loading targets in package `fbcode//third-party-buck/platform010/build/llvm-fb/12` for target `fbcode//third-party-buck/platform010/build/llvm-fb/12:bin/llvm-ar`
    6: Error evaluating build file: `fbcode//third-party-buck/platform010/build/llvm-fb/12:TARGETS`
    7: Traceback (most recent call last):
         * fbcode/third-party-buck/platform010/build/llvm-fb/12/TARGETS:4615, in <module>
             cpp_module_external(
         * tools/build_defs/fbcode_macros/build_defs/cpp_module_external.bzl:56, in cpp_module_external
             clang_modules.gen_tp2_cpp_module(
         * tools/build_defs/fbcode_macros/build_defs/lib/clang_modules.bzl:394, in _gen_tp2_cpp_module
             _gen_module(
         * tools/build_defs/fbcode_macros/build_defs/lib/clang_modules.bzl:324, in _gen_module
             cxx_genrule(
         * tools/build_defs/fbcode_macros/build_defs/native_rules.bzl:107, in cxx_genrule
             fb_native.cxx_genrule(
         * tools/build_defs/fb_native_wrapper.bzl:518, in _fb_native_cxx_genrule
             native.cxx_genrule(**kwargs)
       error: Error coercing attribute `srcs` of `fbcode//third-party-buck/platform010/build/llvm-fb/12:stddef_max_align_t-module`
          --> tools/build_defs/fb_native_wrapper.bzl:518:5
           |
       518 |     native.cxx_genrule(**kwargs)
           |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |

       Error coercing attribute `srcs` of `fbcode//third-party-buck/platform010/build/llvm-fb/12:stddef_max_align_t-module`

       Caused by:
           0: Error coercing attribute `srcs`
           1: Error coercing {"sandboxed_module_header_dir": "lib/clang/stable/include"}
           2: one_of fails, the errors against each alternative in turn were:
              Error coercing "lib/clang/stable/include": Couldn't coerce `lib/clang/stable/include` as a source.
                Error when treated as a target: Invalid absolute target pattern `lib/clang/stable/include` is not allowed: Expected a `:`, a trailing `/...` or the literal `...`.
                Error when treated as a path: Expected file, but got a directory for path `lib/clang/stable/include` in package `fbcode//third-party-buck/platform010/build/llvm-fb/12`.
              Expected value of type `list`, got value with type `dict` (value was `{"sandboxed_module_header_dir": "lib/clang/stable/include"}`)

Buck UI: https://www.internalfb.com/buck2/62dc3bd7-0480-4b3e-b4ad-c2692303f0a5
Jobs completed: 367. Time elapsed: 1.7s.
2023-03-30T16:43:57.089812Z  WARN cli::panic::imp: Warning "event_log_upload_failed": Error finding a cert: No valid cert found
BUILD FAILED
```

Reviewed By: krallin

Differential Revision: D44568313

fbshipit-source-id: fcd7b928343d553ffe31038a2b44badc0fe5ff49