Annotate missing lifetime in IntoFileNameBufIterator hidden type
Summary:
Fixes in Rust 1.67.0:

   error[E0700]: hidden type for `<&'a ForwardRelativePath as into_filename_buf_iterator::IntoFileNameBufIterator>::Iterator` captures lifetime that does not appear in bounds
     --> buck2/app/buck2_core/src/fs/paths/into_filename_buf_iterator.rs:31:9
      |
   27 | impl<'a> IntoFileNameBufIterator for &'a ForwardRelativePath {
      |      -- hidden type `gazebo::ext::iter::Owned<ForwardRelativePathIter<'a>>` captures the lifetime `'a` as defined here
   ...
   31 |         self.iter().owned()
      |         ^^^^^^^^^^^^^^^^^^^

   error[E0700]: hidden type for `<&'a forward_rel_path::ForwardRelativePathBuf as into_filename_buf_iterator::IntoFileNameBufIterator>::Iterator` captures lifetime that does not appear in bounds
     --> buck2/app/buck2_core/src/fs/paths/into_filename_buf_iterator.rs:39:9
      |
   35 | impl<'a> IntoFileNameBufIterator for &'a ForwardRelativePathBuf {
      |      -- hidden type `gazebo::ext::iter::Owned<ForwardRelativePathIter<'a>>` captures the lifetime `'a` as defined here
   ...
   39 |         self.iter().owned()
      |         ^^^^^^^^^^^^^^^^^^^

   error[E0700]: hidden type for `<&'a project::ProjectRelativePath as into_filename_buf_iterator::IntoFileNameBufIterator>::Iterator` captures lifetime that does not appear in bounds
     --> buck2/app/buck2_core/src/fs/paths/into_filename_buf_iterator.rs:47:9
      |
   43 | impl<'a> IntoFileNameBufIterator for &'a ProjectRelativePath {
      |      -- hidden type `gazebo::ext::iter::Owned<ForwardRelativePathIter<'a>>` captures the lifetime `'a` as defined here
   ...
   47 |         self.iter().owned()
      |         ^^^^^^^^^^^^^^^^^^^

   error[E0700]: hidden type for `<&'a project::ProjectRelativePathBuf as into_filename_buf_iterator::IntoFileNameBufIterator>::Iterator` captures lifetime that does not appear in bounds
     --> buck2/app/buck2_core/src/fs/paths/into_filename_buf_iterator.rs:55:9
      |
   51 | impl<'a> IntoFileNameBufIterator for &'a ProjectRelativePathBuf {
      |      -- hidden type `gazebo::ext::iter::Owned<ForwardRelativePathIter<'a>>` captures the lifetime `'a` as defined here
   ...
   55 |         self.iter().owned()
      |         ^^^^^^^^^^^^^^^^^^^

   error: aborting due to 4 previous errors

Reviewed By: dtolnay

Differential Revision: D42900847

fbshipit-source-id: d49217a399495c90b5230bada2a3fe705fc28b35