Allow file changes at the root (#43)
Summary:
I don't claim to understand why, but this seems to keep happening to me when I'm setting buck2 up in a private repo.

Running `RUST_BACKTRACE=1 buck run ...` produced:

```
[2022-12-10T18:58:58.032-08:00] thread 'notify-rs fsevents loop' panicked at 'a file/dir in the repo must have a parent, but `root//` had none', buck2_common/src/dice/file_ops.rs:187:5
[2022-12-10T18:58:58.032-08:00] stack backtrace:
[2022-12-10T18:58:58.032-08:00]    0:        0x104b988c4 - std::backtrace_rs::backtrace::libunwind::trace::hece5cd97d7ff3f91
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
[2022-12-10T18:58:58.032-08:00]    1:        0x104b988c4 - std::backtrace_rs::backtrace::trace_unsynchronized::h11e2344cfa8655d5
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
[2022-12-10T18:58:58.032-08:00]    2:        0x104b988c4 - std::sys_common::backtrace::_print_fmt::h634b091d56b54f05
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/sys_common/backtrace.rs:66:5
[2022-12-10T18:58:58.032-08:00]    3:        0x104b988c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h81da8dd6c6b18539
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/sys_common/backtrace.rs:45:22
[2022-12-10T18:58:58.032-08:00]    4:        0x104bb720c - core::fmt::write::ha734a2d93e3a9a62
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/core/src/fmt/mod.rs:1202:17
[2022-12-10T18:58:58.032-08:00]    5:        0x104b91060 - std::io::Write::write_fmt::h8c69c70c7ecba05b
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/io/mod.rs:1679:15
[2022-12-10T18:58:58.032-08:00]    6:        0x104b9a50c - std::sys_common::backtrace::_print::h6d2807747db383e7
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/sys_common/backtrace.rs:48:5
[2022-12-10T18:58:58.032-08:00]    7:        0x104b9a50c - std::sys_common::backtrace::print::h07269e00f341ae20
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/sys_common/backtrace.rs:35:9
[2022-12-10T18:58:58.032-08:00]    8:        0x104b9a50c - std::panicking::default_hook::{{closure}}::h1d2c0e05af7977f1
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/panicking.rs:267:22
[2022-12-10T18:58:58.032-08:00]    9:        0x104b9a230 - std::panicking::default_hook::hf9193a1b36f532f9
[2022-12-10T18:58:58.032-08:00]                                at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/panicking.rs:286:9
[2022-12-10T18:58:58.032-08:00]   10:        0x102d5fb00 - cli::panic::initialize::{{closure}}::h17a22d7ec0bfa34a
BUILD FAILED
Command failed: Buck daemon event bus encountered an error

Caused by:
    0: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
    1: error reading a body from connection: broken pipe
    2: broken pipe

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/8b705839cd656d202e920efa8769cbe43a5ee269/library/std/src/backtrace.rs:333:13
   3: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
```

This change seems to fix it with no ill side-effects as far as I can see (though I don't have much experience with this codebase or as an user of buck2)

Refs: https://github.com/facebookincubator/buck2/issues/14

Pull Request resolved: https://github.com/facebookincubator/buck2/pull/43

Reviewed By: ndmitchell

Differential Revision: D42012779

Pulled By: bigfootjon

fbshipit-source-id: a0ef8b63adb2083ed299bd14f61d57bab67c4f48