be explicit about linking executable when producing linker map; take 2
Summary:
Original diff: D44337320

Original diff caused analysis error for optimised builds:
```
Caused by:
    Traceback (most recent call last):
      * fbcode/buck2/prelude/cxx/cxx.bzl:237, in <module>
          output, comp_db_info, xcode_data_info = cxx_executable(ctx, params)
      * fbcode/buck2/prelude/cxx/cxx_executable.bzl:468, in cxx_executable
          (linker_map, binary_for_linker_map) = _linker_map(
      * fbcode/buck2/prelude/cxx/cxx_executable.bzl:549, in _linker_map
          cxx_link(
      * fbcode/buck2/prelude/cxx/link.bzl:168, in cxx_link
          final_output = output if not (executable_link and cxx_use_bolt(ctx)) else bol...
      * fbcode/buck2/prelude/cxx/cxx_bolt.bzl:59, in bolt
          postbolt_output = ctx.actions.declare_output(output_name)
    error: Multiple artifacts and/or metadata files are declared at the same output location `REDACTED.linker-map-binary`.
      --> fbcode/buck2/prelude/cxx/cxx_bolt.bzl:59:23
       |
    59 |     postbolt_output = ctx.actions.declare_output(output_name)
       |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |

```

The difference between original diff and this diff is that we now do not allow bolt optimisation when linker map is produced. Use `generate_dwp` parameter for that as well (which is only used when linker map is generated to avoid extra actions) and rename it accordingly.

Reviewed By: chatura-atapattu

Differential Revision: D44385946

fbshipit-source-id: 75c4d8f232844fd70924491d2503732fdd1c2aea